version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    command: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
  db:
    image: "mysql:8.0.30"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "admin"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "root"
      MYSQL_ROOT_PASSWORD: "root"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
